export const Data = [
  {
    id: 1,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 2,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 3,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 4,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 5,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 6,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 7,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 8,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 9,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
  {
    id: 10,
    title: "IPHONE 11 Pro Max",
    price: 800,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus ratione non voluptate corrupti commodi hic earum, enim dolorem! Culpa perspiciatis provident velit eaque dolores quae atque! Nihil assumenda odit quisquam hic corporis est facere voluptatum. Quaerat sed nisi impedit officia quod officiis sequi, facilis fugiat, ab doloremque dignissimos ducimus ipsum",
    img: "/assets/water.jpg",
  },
];
